[package]
name = "xc_lexer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thin-vec = "0.2.13"
unicode-xid = "0.2.4"
xc_span = { version = "0.1.0", path = "../xc_span" }
